{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:53.133Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:53.174Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:53.176Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:53.177Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:53.276Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:53.277Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:53.389Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:53.391Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:53.423Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:53.428Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:53.788Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:53.790Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:54.025Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:54.026Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:54.146Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:54.152Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:54.594Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:54.597Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:55.341Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:55.342Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:55.585Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:55.587Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:55.621Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:55.622Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:56.070Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:56.071Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:56.674Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:56.675Z"}
{"error":{"name":"MongoError","message":"failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]"},"level":"error","message":"Error generating response. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' }","timestamp":"2017-09-06T21:22:57.193Z"}
{"level":"error","message":"Uncaught internal server error. { MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)\n  name: 'MongoError',\n  message: 'failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]' } MongoError: failed to connect to server [ds139242.mlab.com:39242] on first connect [MongoError: getaddrinfo ENOTFOUND ds139242.mlab.com ds139242.mlab.com:39242]\n    at Pool.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:329:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:280:12)\n    at Connection.g (events.js:292:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (/Users/dom/Documents/celecare-node/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:187:49)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at connectErrorNT (net.js:1021:8)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)","timestamp":"2017-09-06T21:22:57.194Z"}
